[package]
name = "extractfa"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@embl.de>"]
edition = "2018"
publish = false

[dependencies]
bio = "0.41.0"
flate2 = "1.0.20"
pico-args = "0.5.0"
indicatif = "0.16.2"

[[bin]]
name = "extractfa"
path = "main.rs"
