stages:
  sample proGenomes:
    cmd: cargo run --release --manifest-path src/samplefa/Cargo.toml -- --input data/progenomes/freeze12.contigs.representatives.fasta.gz
      --output data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
      --seed 42 --min-size 250000 --total 5000
    deps:
    - data/progenomes/freeze12.contigs.representatives.fasta.gz
    - src/samplefa/Cargo.lock
    - src/samplefa/Cargo.toml
    - src/samplefa/main.rs
    outs:
    - data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
  deduplicate selected proGenomes contigs:
    cmd: python -m src.dedupbyani --input data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
      --list data/progenomes/freeze12.contigs.representatives.deduplicated.txt --6genomes
      data/6genomes --9genomes data/9genomes --total 5000
    deps:
    - data/6genomes/Anabaena_variabilis_ATCC_29413_NC_007413.1.gbk
    - data/6genomes/Pseudomonas_fluorescens_Pf-5_NC_004129.6.gbk
    - data/6genomes/Saccharopolyspora_erythraea_NRRL_2338_AM420293.1.gbk
    - data/6genomes/Salinispora_tropica_CNB-440_NC_009380.1.gbk
    - data/6genomes/Sorangium_cellulosum_So_ce_56_AM746676.1.gbk
    - data/6genomes/Streptomyces_griseus_griseus_NBRC_13350_AP009493.1.gbk
    - data/9genomes/Kutzneria_sp_744_KK037166.1.gbk
    - data/9genomes/Micromonospora_sp_ATCC_39149_GG657738.1.gbk
    - data/9genomes/Micromonospora_sp_M42_KK037233.1.gbk
    - data/9genomes/Streptomyces_albidoflavus_strain_J1074_DS999645.1.gbk
    - data/9genomes/Streptomyces_ghanaensis_ATCC_14672_DS999641.1.gbk
    - data/9genomes/Streptomyces_ghanaensis_ATCC_14672_DS999642.1.gbk
    - data/9genomes/Streptomyces_hygroscopicus_ATCC_53653_GG657754.1.gbk
    - data/9genomes/Streptomyces_pristinaespiralis_ATCC_25486_CM000950.1.gbk
    - data/9genomes/Streptomyces_sp_AA4_GG657746.1.gbk
    - data/9genomes/Streptomyces_sp_AA4_GG657747.1.gbk
    - data/9genomes/Streptomyces_sp_C_GG657750.1.gbk
    - data/9genomes/Streptomyces_sp_C_GG657751.1.gbk
    - data/9genomes/Streptomyces_sp_C_GG657752.1.gbk
    - data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
    outs:
    - data/progenomes/freeze12.contigs.representatives.deduplicated.txt:
        cache: false
  extract deduplicated proGenomes contigs:
    cmd: cargo run --release --manifest-path src/extractfa/Cargo.toml -- --input data/progenomes/freeze12.contigs.representatives.fasta.gz
      --list data/progenomes/freeze12.contigs.representatives.deduplicated.txt --output
      data/progenomes/freeze12.contigs.representatives.deduplicated.fasta
    deps:
    - data/progenomes/freeze12.contigs.representatives.deduplicated.txt
    - data/progenomes/freeze12.contigs.representatives.fasta.gz
    outs:
    - data/progenomes/freeze12.contigs.representatives.deduplicated.fasta
  analyze deduplicated proGenomes contigs:
    cmd: antismash -v --skip-zip-file --genefinding-tool prodigal-m --output-dir data/antismash/freeze12.contigs.representatives.deduplicated
      --output-basename deduplicated data/progenomes/freeze12.contigs.representatives.deduplicated.fasta
    deps:
    - data/progenomes/freeze12.contigs.representatives.deduplicated.fasta
    outs:
    - data/antismash/freeze12.contigs.representatives.deduplicated/deduplicated.gbk
    - data/antismash/freeze12.contigs.representatives.deduplicated/deduplicated.json
  remove biosynthetic regions from proGenomes contigs:
    cmd: python -m src.delregions --input data/antismash/freeze12.contigs.representatives.deduplicated/deduplicated.gbk
      --list data/progenomes/freeze12.contigs.representatives.deduplicated.txt --output
      data/progenomes/freeze12.contigs.representatives.cleaned.fasta
    deps:
    - data/antismash/freeze12.contigs.representatives.deduplicated/deduplicated.gbk
    - data/progenomes/freeze12.contigs.representatives.deduplicated.txt
    outs:
    - data/progenomes/freeze12.contigs.representatives.cleaned.fasta
  analyze cleaned proGenomes contigs:
    cmd: antismash -v --skip-zip-file --genefinding-tool prodigal-m --output-dir data/antismash/freeze12.contigs.representatives.cleaned
      --output-basename cleaned data/progenomes/freeze12.contigs.representatives.cleaned.fasta
    deps:
    - data/progenomes/freeze12.contigs.representatives.cleaned.fasta
    outs:
    - data/antismash/freeze12.contigs.representatives.cleaned/cleaned.gbk
    - data/antismash/freeze12.contigs.representatives.cleaned/cleaned.json
  make MIBiG_1_3 embeddings:
    cmd: python -m src.embed --input data/antismash/freeze12.contigs.representatives.cleaned/cleaned.gbk
      --list data/progenomes/freeze12.contigs.representatives.deduplicated.txt --mibig
      data/mibig/ --version 1.3 --output-prefix data/embeddings/mibig-1.3.proG2 --retire
      data/mibig/retire.txt
    deps:
    - data/antismash/freeze12.contigs.representatives.cleaned/cleaned.gbk
    - data/mibig/mibig-1.3.gbk.tar.gz
    - data/mibig/mibig-1.3.json.tar.gz
    - data/mibig/mibig-1.4.json.tar.gz
    - data/mibig/mibig-2.0.json.tar.gz
    - data/mibig/retire.txt
    - data/progenomes/freeze12.contigs.representatives.deduplicated.txt
    outs:
    - data/embeddings/mibig-1.3.proG2.clusters.tsv:
        cache: false
    - data/embeddings/mibig-1.3.proG2.fna
    - data/embeddings/mibig-1.3.proG2.gbk
  make MIBiG_2_0 embeddings:
    cmd: python -m src.embed --input data/antismash/freeze12.contigs.representatives.cleaned/cleaned.gbk
      --list data/progenomes/freeze12.contigs.representatives.deduplicated.txt --mibig
      data/mibig/ --version 2.0 --output-prefix data/embeddings/mibig-2.0.proG2 --retire
      data/mibig/retire.txt
    deps:
    - data/antismash/freeze12.contigs.representatives.cleaned/cleaned.gbk
    - data/mibig/mibig-1.3.json.tar.gz
    - data/mibig/mibig-1.4.json.tar.gz
    - data/mibig/mibig-2.0.gbk.tar.gz
    - data/mibig/mibig-2.0.json.tar.gz
    - data/mibig/retire.txt
    - data/progenomes/freeze12.contigs.representatives.deduplicated.txt
    outs:
    - data/embeddings/mibig-2.0.proG2.clusters.tsv:
        cache: false
    - data/embeddings/mibig-2.0.proG2.fna
    - data/embeddings/mibig-2.0.proG2.gbk
  index MIBiG_1_3 FASTA embedding:
    cmd: samtools faidx data/embeddings/mibig-1.3.proG2.fna
    deps:
    - data/embeddings/mibig-1.3.proG2.fna
    outs:
    - data/embeddings/mibig-1.3.proG2.fna.fai
  index MIBiG_2_0 FASTA embedding:
    cmd: samtools faidx data/embeddings/mibig-2.0.proG2.fna
    deps:
    - data/embeddings/mibig-2.0.proG2.fna
    outs:
    - data/embeddings/mibig-2.0.proG2.fna.fai
  annotate MIBiG_1_3 embeddings with Pfam_33_1:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-1.3.proG2.fna.fai
      data/hmms/Pfam-v33.1.hmm.gz
    deps:
    - data/embeddings/mibig-1.3.proG2.fna.fai
    - data/hmms/Pfam-v33.1.hmm.gz
    outs:
    - data/embeddings/mibig-1.3.proG2.Pfam-v33.1.features.tsv
  annotate MIBiG_1_3 embeddings with Pfam_34_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-1.3.proG2.fna.fai
      data/hmms/Pfam-v34.0.hmm.gz
    deps:
    - data/embeddings/mibig-1.3.proG2.fna.fai
    - data/hmms/Pfam-v34.0.hmm.gz
    outs:
    - data/embeddings/mibig-1.3.proG2.Pfam-v34.0.features.tsv
  annotate MIBiG_1_3 embeddings with Tigrfam_15_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-1.3.proG2.fna.fai
      data/hmms/Tigrfam-v15.0.hmm.gz
    deps:
    - data/embeddings/mibig-1.3.proG2.fna.fai
    - data/hmms/Tigrfam-v15.0.hmm.gz
    outs:
    - data/embeddings/mibig-1.3.proG2.Tigrfam-v15.0.features.tsv
  annotate MIBiG_1_3 embeddings with Pfam_31_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-1.3.proG2.fna.fai
      data/hmms/Pfam-v31.0.hmm.gz
    deps:
    - data/embeddings/mibig-1.3.proG2.fna.fai
    - data/hmms/Pfam-v31.0.hmm.gz
    outs:
    - data/embeddings/mibig-1.3.proG2.Pfam-v31.0.features.tsv
  annotate MIBiG_2_0 embeddings with Tigrfam_15_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-2.0.proG2.fna.fai
      data/hmms/Tigrfam-v15.0.hmm.gz
    deps:
    - data/embeddings/mibig-2.0.proG2.fna.fai
    - data/hmms/Tigrfam-v15.0.hmm.gz
    outs:
    - data/embeddings/mibig-2.0.proG2.Tigrfam-v15.0.features.tsv
  annotate MIBiG_2_0 embeddings with Pfam_31_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-2.0.proG2.fna.fai
      data/hmms/Pfam-v31.0.hmm.gz
    deps:
    - data/embeddings/mibig-2.0.proG2.fna.fai
    - data/hmms/Pfam-v31.0.hmm.gz
    outs:
    - data/embeddings/mibig-2.0.proG2.Pfam-v31.0.features.tsv
  annotate MIBiG_2_0 embeddings with Pfam_33_1:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-2.0.proG2.fna.fai
      data/hmms/Pfam-v33.1.hmm.gz
    deps:
    - data/embeddings/mibig-2.0.proG2.fna.fai
    - data/hmms/Pfam-v33.1.hmm.gz
    outs:
    - data/embeddings/mibig-2.0.proG2.Pfam-v33.1.features.tsv
  annotate MIBiG_2_0 embeddings with Pfam_34_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-2.0.proG2.fna.fai
      data/hmms/Pfam-v34.0.hmm.gz
    deps:
    - data/embeddings/mibig-2.0.proG2.fna.fai
    - data/hmms/Pfam-v34.0.hmm.gz
    outs:
    - data/embeddings/mibig-2.0.proG2.Pfam-v34.0.features.tsv
  annotate MIBiG_1_3 embeddings with Pfam_35_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-1.3.proG2.fna.fai
      data/hmms/Pfam-v35.0.hmm.gz
    deps:
    - data/embeddings/mibig-1.3.proG2.fna.fai
    - data/hmms/Pfam-v35.0.hmm.gz
    outs:
    - data/embeddings/mibig-1.3.proG2.Pfam-v35.0.features.tsv
  annotate MIBiG_2_0 embeddings with Pfam_35_0:
    cmd: src/annotate/gecco-annotate-slurm.sh data/embeddings/mibig-2.0.proG2.fna.fai
      data/hmms/Pfam-v35.0.hmm.gz
    deps:
    - data/embeddings/mibig-2.0.proG2.fna.fai
    - data/hmms/Pfam-v35.0.hmm.gz
    outs:
    - data/embeddings/mibig-2.0.proG2.Pfam-v35.0.features.tsv
