stages:
  sample proGenomes:
    cmd: cargo run --release --manifest-path src/samplefa/Cargo.toml -- --input data/progenomes/freeze12.contigs.representatives.fasta.gz
      --output data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
      --seed 42 --min-size 250000 --total 5000
    deps:
    - data/progenomes/freeze12.contigs.representatives.fasta.gz
    - src/samplefa/Cargo.lock
    - src/samplefa/Cargo.toml
    - src/samplefa/main.rs
    outs:
    - data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
  analyze proGenomes clusters:
    cmd: antismash -v --skip-zip-file --genefinding-tool prodigal-m --output-dir data/progenomes/antismash/
      --output-basename freeze12.contigs.representatives.randomly_selected data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
    deps:
    - data/progenomes/freeze12.contigs.representatives.randomly_selected.fasta
    outs:
    - data/progenomes/antismash/freeze12.contigs.representatives.randomly_selected.gbk
    - data/progenomes/antismash/freeze12.contigs.representatives.randomly_selected.json
